var typed = new Typed(".typing", {
  strings: [
    "A modern touch",
    "for a modern university.",
    " ",
    "Your university, simplified.",
    " ",
    "Building a better campus,",
    "together.",
    " ",
    "Your journey starts here.",
    " ",
    "It's not just a map,",
    "it's your university compass.",
    " ",
  ],
  typeSpeed: 100,
  backSpeed: 50,
  loop: true,
});